// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	openRepository: (path: string) => typedError<RepoSummary, GitError>(__TAURI_INVOKE("open_repository", { path })),
	/**  A channel rather than a return value (INV-02); dropping it cancels the walk. */
	loadCommits: (repo: RepoId, onChunk: Channel<GraphChunk>) => typedError<null, GitError>(__TAURI_INVOKE("load_commits", { repo, onChunk })),
	commitDetails: (repo: RepoId, rev: string) => typedError<CommitDetails, GitError>(__TAURI_INVOKE("commit_details", { repo, rev })),
	commitFiles: (repo: RepoId, rev: string) => typedError<FileEntry[], GitError>(__TAURI_INVOKE("commit_files", { repo, rev })),
};

/* Types */
/**  specta follows serde, so a DTO without `camelCase` reads `undefined` in the UI. */
export type AppInfo = {
	version: string,
	logPath: string,
	debugBuild: boolean,
};

export type Branch = {
	name: string,
	fullName: string,
	kind: BranchKind,
	oid: string,
	isHead: boolean,
};

export type BranchKind = "local" | "remote";

export type CommitDetails = {
	oid: string,
	parents: string[],
	summary: string,
	body: string,
	author: Signature,
	committer: Signature,
};

export type CommitRow = {
	oid: string,
	/**  Git order: the first parent is the mainline, which lane allocation relies on. */
	parents: string[],
	summary: string,
	authorName: string,
	authorEmail: string,
	/**
	 *  Seconds since the Unix epoch.
	 * 
	 *  specta refuses `i64` by default to guard against precision loss. Unix seconds
	 *  stay far below 2^53, so a plain TypeScript number is exact here.
	 */
	timestamp: number,
	tzOffsetMinutes: number,
};

export type EdgeKind = "direct" | "merge" | "crossing";

export type FileEntry = {
	path: string,
	oldPath: string | null,
	status: FileStatus,
};

export type FileStatus = "added" | "modified" | "deleted" | "renamed" | "copied";

export type GitCommandError = {
	command: string,
	exitCode: number | null,
	stdout: string,
	stderr: string,
};

export type GitError = { kind: "command"; data: GitCommandError } | { kind: "repoNotFound"; data: string } | { kind: "repoBusy"; data: string } | { kind: "invalidState"; data: string } | { kind: "io"; data: string } | { kind: "internal"; data: string };

/**  Commits arrive with their lane placement so the UI never computes layout (INV-02). */
export type GraphChunk = {
	commits: CommitRow[],
	lanes: LaneAssignment[],
	edges: GraphEdge[],
	maxLane: number,
	isLast: boolean,
};

export type GraphEdge = {
	fromRow: number,
	fromLane: number,
	toRow: number,
	toLane: number,
	color: number,
	kind: EdgeKind,
};

/**  Assuming "HEAD is a branch" crashes on an unborn or detached checkout (INV-07). */
export type Head = { kind: "branch"; name: string; oid: string } | { kind: "detached"; oid: string } | { kind: "unborn"; name: string };

export type LaneAssignment = {
	row: number,
	lane: number,
	color: number,
	kind: NodeKind,
};

export type NodeKind = "normal" | "merge" | "root" | "workingTree";

export type RepoId = number;

export type RepoStatus = {
	staged: number,
	unstaged: number,
	untracked: number,
	conflicted: number,
};

export type RepoSummary = {
	repo: RepoId,
	root: string,
	name: string,
	isBare: boolean,
	head: Head,
	branches: Branch[],
	tags: Tag[],
	status: RepoStatus,
};

export type Signature = {
	name: string,
	email: string,
	timestamp: number,
	tzOffsetMinutes: number,
};

export type Tag = {
	name: string,
	fullName: string,
	oid: string,
	isAnnotated: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

