// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	openRepository: (path: string) => typedError<RepoSummary, GitError>(__TAURI_INVOKE("open_repository", { path })),
	/**  A channel rather than a return value (INV-02); dropping it cancels the walk. */
	loadCommits: (repo: RepoId, query: CommitQuery, onChunk: Channel<GraphChunk>) => typedError<null, GitError>(__TAURI_INVOKE("load_commits", { repo, query, onChunk })),
	commitDetails: (repo: RepoId, rev: string) => typedError<CommitDetails, GitError>(__TAURI_INVOKE("commit_details", { repo, rev })),
	commitFiles: (repo: RepoId, rev: string) => typedError<FileEntry[], GitError>(__TAURI_INVOKE("commit_files", { repo, rev })),
	diffFile: (repo: RepoId, spec: DiffSpec, path: string, options: DiffOptions) => typedError<FileDiff, GitError>(__TAURI_INVOKE("diff_file", { repo, spec, path, options })),
};

/* Types */
export type Algorithm = "histogram" | "myers";

/**  specta follows serde, so a DTO without `camelCase` reads `undefined` in the UI. */
export type AppInfo = {
	version: string,
	logPath: string,
	debugBuild: boolean,
};

export type Branch = {
	name: string,
	fullName: string,
	kind: BranchKind,
	oid: string,
	isHead: boolean,
};

export type BranchKind = "local" | "remote";

export type CommitDetails = {
	oid: string,
	parents: string[],
	summary: string,
	body: string,
	author: Signature,
	committer: Signature,
};

export type CommitQuery = {
	author?: string | null,
	message?: string | null,
	oidPrefix?: string | null,
	since?: number | null,
	until?: number | null,
	path?: string | null,
};

export type CommitRow = {
	oid: string,
	/**  Git order: the first parent is the mainline, which lane allocation relies on. */
	parents: string[],
	summary: string,
	authorName: string,
	authorEmail: string,
	/**  specta refuses `i64`; Unix seconds stay far below 2^53, so a number is exact. */
	timestamp: number,
	tzOffsetMinutes: number,
};

export type DiffOptions = {
	algorithm: Algorithm,
	contextLines: number,
	ignoreWhitespace: Whitespace,
	ignoreBlankLines: boolean,
	wordDiff: boolean,
};

export type DiffRow = { kind: "context"; old: number; new: number; text: string } | { kind: "delete"; old: number; text: string; inline: ([number, number])[] } | { kind: "insert"; new: number; text: string; inline: ([number, number])[] } | { kind: "collapsed"; count: number };

export type DiffSpec = { kind: "commitVsParent"; oid: string } | { kind: "commitVsCommit"; a: string; b: string };

export type EdgeKind = "direct" | "merge" | "crossing";

export type EolInfo = {
	old: LineEnding,
	new: LineEnding,
	normalized: boolean,
};

export type FileDiff = { kind: "text"; hunks: Hunk[]; eol: EolInfo; lossyEncoding: boolean; 
/**  Language hint for Lezer. Highlighting itself is a frontend concern (INV-01). */
language: string | null } | { kind: "eolOnly"; from: LineEnding; to: LineEnding } | { kind: "binary"; oldSize: number; newSize: number } | { kind: "image"; oldSize: number; newSize: number; mime: string } | { kind: "tooLarge"; size: number } | { kind: "unchanged" };

export type FileEntry = {
	path: string,
	oldPath: string | null,
	status: FileStatus,
};

export type FileStatus = "added" | "modified" | "deleted" | "renamed" | "copied";

export type GitCommandError = {
	command: string,
	exitCode: number | null,
	stdout: string,
	stderr: string,
};

export type GitError = { kind: "command"; data: GitCommandError } | { kind: "repoNotFound"; data: string } | { kind: "repoBusy"; data: string } | { kind: "invalidState"; data: string } | { kind: "io"; data: string } | { kind: "internal"; data: string };

/**  Commits arrive with their lane placement so the UI never computes layout (INV-02). */
export type GraphChunk = {
	commits: CommitRow[],
	lanes: LaneAssignment[],
	edges: GraphEdge[],
	maxLane: number,
	isLast: boolean,
};

export type GraphEdge = {
	fromRow: number,
	fromLane: number,
	toRow: number,
	toLane: number,
	color: number,
	kind: EdgeKind,
};

/**  Assuming "HEAD is a branch" crashes on an unborn or detached checkout (INV-07). */
export type Head = { kind: "branch"; name: string; oid: string } | { kind: "detached"; oid: string } | { kind: "unborn"; name: string };

export type Hunk = {
	oldStart: number,
	oldLines: number,
	newStart: number,
	newLines: number,
	header: string,
	rows: DiffRow[],
};

export type LaneAssignment = {
	row: number,
	lane: number,
	color: number,
	kind: NodeKind,
};

export type LineEnding = "lf" | "crlf" | "cr" | "mixed" | "none";

export type NodeKind = "normal" | "merge" | "root" | "workingTree";

export type RepoId = number;

export type RepoStatus = {
	staged: number,
	unstaged: number,
	untracked: number,
	conflicted: number,
};

export type RepoSummary = {
	repo: RepoId,
	root: string,
	name: string,
	isBare: boolean,
	head: Head,
	branches: Branch[],
	tags: Tag[],
	status: RepoStatus,
};

export type Signature = {
	name: string,
	email: string,
	timestamp: number,
	tzOffsetMinutes: number,
};

export type Tag = {
	name: string,
	fullName: string,
	oid: string,
	isAnnotated: boolean,
};

export type Whitespace = "none" | "trailing" | "all";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

