// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Returns application metadata.
	 * 
	 *  This is the walking-skeleton command: it proves the whole
	 *  Rust → specta → TypeScript → Svelte chain is wired correctly.
	 */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
};

/* Types */
/**
 *  Static facts about the running application, shown in the status bar and in bug reports.
 * 
 *  `rename_all = "camelCase"` is mandatory on every DTO: specta follows serde for field
 *  names, and mixing `snake_case` and `camelCase` across the IPC boundary is a constant
 *  source of silent `undefined` reads in the UI.
 */
export type AppInfo = {
	version: string,
	/**  Absolute path of the current log file, so the user can open it from the UI. */
	logPath: string,
	/**  Whether this is a debug build. The UI shows developer affordances only then. */
	debugBuild: boolean,
};

