/**
 * The frontend's only doorway to the backend.
 *
 * Components import from here, never from `@tauri-apps/api` directly and never from
 * `bindings.ts`. That keeps one place to add logging, cancellation and error mapping.
 *
 * `bindings.ts` is generated by `cargo run -p cogit --bin export-bindings` and must not
 * be edited by hand (INV-10).
 */

import { Channel } from "@tauri-apps/api/core";

import { commands } from "./bindings";
import type { GitError, GraphChunk, RepoId } from "./bindings";

export type {
  AppInfo,
  Branch,
  BranchKind,
  CommitRow,
  GitError,
  GraphChunk,
  GraphEdge,
  Head,
  LaneAssignment,
  RepoId,
  RepoSummary,
} from "./bindings";

/**
 * A backend failure that keeps its structure.
 *
 * The raw `GitError` is carried through untouched so the Git Error Dialog can show the
 * exact `stdout` and `stderr` Git produced (INV-05). Flattening it to a string here
 * would destroy the only information worth having.
 */
export class CogitError extends Error {
  readonly detail: GitError;

  constructor(detail: GitError) {
    super(describeError(detail));
    this.name = "CogitError";
    this.detail = detail;
  }

  /** Whether this came from a `git` CLI invocation and deserves the raw-output dialog. */
  get isCommandFailure(): boolean {
    return this.detail.kind === "command";
  }
}

/** One-line summary for toasts and the status bar. The dialog shows far more. */
function describeError(error: GitError): string {
  switch (error.kind) {
    case "command":
      return `${error.data.command} failed with exit code ${error.data.exitCode ?? "unknown"}`;
    case "repoNotFound":
      return `Not a Git repository: ${error.data}`;
    case "repoBusy":
      return `Repository is busy: ${error.data}`;
    case "invalidState":
      return `Invalid repository state: ${error.data}`;
    case "io":
      return `I/O error: ${error.data}`;
    case "internal":
      return `Internal error: ${error.data}`;
  }
}

export async function getAppInfo() {
  return await commands.appInfo();
}

/**
 * Opens the repository containing `path`.
 *
 * @throws {CogitError} when the backend reports a failure.
 */
export async function openRepository(path: string) {
  const result = await commands.openRepository(path);
  if (result.status === "error") {
    throw new CogitError(result.error);
  }
  return result.data;
}

/**
 * Streams the commit graph, calling `onChunk` for each instalment.
 *
 * @throws {CogitError} when the backend reports a failure.
 */
export async function loadCommits(repo: RepoId, onChunk: (chunk: GraphChunk) => void) {
  const channel = new Channel<GraphChunk>();
  channel.onmessage = onChunk;
  const result = await commands.loadCommits(repo, channel);
  if (result.status === "error") {
    throw new CogitError(result.error);
  }
}
