/**
 * The frontend's only doorway to the backend.
 *
 * Components import from here, never from `@tauri-apps/api` directly and never from
 * `bindings.ts`. That keeps one place to add logging, cancellation and error mapping.
 *
 * `bindings.ts` is generated by `cargo test -p cogit` and must not be edited by hand
 * (INV-10). Regenerate it after changing any command or DTO.
 */

import { commands } from "./bindings";

export type { AppInfo } from "./bindings";

/**
 * Reads application metadata.
 *
 * This is the walking-skeleton round-trip: if it resolves, the whole
 * Rust → specta → TypeScript → Svelte chain is wired correctly.
 */
export async function getAppInfo() {
  return await commands.appInfo();
}
