mod apply;
mod blame;
mod blobs;
mod branches;
mod commit;
mod commit_write;
mod conflicts;
mod error;
mod find;
mod history;
mod hooks;
mod interactive;
mod merging;
mod network;
mod operations;
mod progress;
mod reflog;
mod replay;
mod repo;
mod runner;
mod search;
mod staging;
mod stash;
mod state;
mod status;
mod submodules;
mod surgery;
mod tags;
mod worktree;

pub use blame::BlameLine;
pub use blobs::{DiffSides, DiffSpec};
pub use branches::CheckoutTarget;
pub use commit::{CommitDetails, DEFAULT_SIMILARITY, FileEntry, FileMode, FileStatus, Signature};
pub use commit_write::CommitRequest;
pub use conflicts::{ConflictSide, ConflictSides, ConflictText};
pub use error::{GitCommandError, GitError};
pub use find::{Found, FoundKind};
pub use history::CommitRow;
pub use hooks::{Hook, HookOverview, HookRun, HookSource, HookState};
pub use interactive::{TodoAction, TodoEntry, render_todo};
pub use merging::MergeOptions;
pub use network::{auth_header, wants_auth};
pub use operations::RebaseOptions;
pub use progress::{RebaseProgress, RebaseStep};
pub use reflog::ReflogEntry;
pub use repo::{Branch, BranchKind, Head, RepoHandle, Tag};
pub use runner::{CommandSink, GitOutput, redact_command};
pub use search::CommitQuery;
pub use stash::{StashEntry, StashOptions};
pub use state::RepoState;
pub use status::RepoStatus;
pub use submodules::{Submodule, SubmoduleState};
pub use tags::TagRequest;
pub use worktree::WorktreeFiles;

pub type Result<T> = std::result::Result<T, GitError>;
