mod blobs;
mod branches;
mod commit;
mod commit_write;
mod error;
mod history;
mod merging;
mod network;
mod operations;
mod reflog;
mod replay;
mod repo;
mod runner;
mod search;
mod staging;
mod stash;
mod state;
mod status;
mod tags;
mod worktree;

pub use blobs::{DiffSides, DiffSpec};
pub use branches::CheckoutTarget;
pub use commit::{CommitDetails, FileEntry, FileStatus, Signature};
pub use commit_write::CommitRequest;
pub use error::{GitCommandError, GitError};
pub use history::CommitRow;
pub use merging::MergeOptions;
pub use operations::RebaseOptions;
pub use reflog::ReflogEntry;
pub use repo::{Branch, BranchKind, Head, RepoHandle, Tag};
pub use runner::{CommandSink, GitOutput};
pub use search::CommitQuery;
pub use stash::{StashEntry, StashOptions};
pub use state::RepoState;
pub use status::RepoStatus;
pub use tags::TagRequest;
pub use worktree::WorktreeFiles;

pub type Result<T> = std::result::Result<T, GitError>;
