// node scripts/bench/set-budgets.mjs <run.json> — rewrites budgets.mjs from a full run.
// A budget is the median with room for a busy machine and a frame of quantisation, so
// `--check` fails on a regression, not on the weather (doc/15-benchmark.md, §5).

import { readFile, writeFile } from "node:fs/promises";

const [path] = process.argv.slice(2);
if (!path) {
  console.error("usage: node scripts/bench/set-budgets.mjs <run.json>");
  process.exit(2);
}
const run = JSON.parse(await readFile(path, "utf8"));
const budgets = run.results
  .filter((r) => r.median !== null && !r.variant && (r.condition === "warm" || r.id.startsWith("app.")))
  .map((r) => ({ id: r.id, set: r.set, condition: r.condition, median: Math.ceil(r.median * 1.25 + 8) }))
  .sort((a, b) => a.id.localeCompare(b.id) || a.set.localeCompare(b.set));

const lines = budgets.map((b) => `  { id: "${b.id}", set: "${b.set}", condition: "${b.condition}", median: ${b.median} },`);
const source = `// Generated by set-budgets.mjs from ${path.replaceAll("\\", "/")} (${run.env?.commit ?? "?"}):
// median × 1.25 + 8 ms, measured with --hidden --cores 16-31.
export const BUDGETS = [
${lines.join("\n")}
];
`;
await writeFile(new URL("./budgets.mjs", import.meta.url), source);
console.log(`${budgets.length} budgets written`);
